package com.civicdesk.module.auditlog.enums;

public enum AuditAction {
    // IAM
    REGISTER,
    LOGIN,
    LOGOUT,
    CREATE_USER,
    UPDATE_STATUS,
    SET_PASSWORD,
    SEED_ADMIN,

    // CitizenProfile
    REGISTER_CITIZEN,
    UPDATE_PROFILE,
    UPLOAD_DOCUMENT,
    VERIFY_DOCUMENT,
    ISSUE_DOCUMENT,

    // ServiceRequest
    CREATE_SERVICE,
    UPDATE_SERVICE,
    SUBMIT_REQUEST,
    UPDATE_REQUEST_STATUS,

    // Permit
    CREATE_PERMIT,
    RENEW_PERMIT,
    SCHEDULE_INSPECTION,
    SUBMIT_INSPECTION,
    REQUEST_DOCUMENTS,
    PERMIT_DECISION,

    // Grievance
    CREATE_GRIEVANCE,
    UPDATE_GRIEVANCE,
    CLOSE_GRIEVANCE,
    REOPEN_GRIEVANCE,
    ASSIGN_FIELD_OFFICER,
    RESOLVE_GRIEVANCE,
    CREATE_GRIEVANCE_ACTION,
    UPDATE_GRIEVANCE_ACTION
}
